version: "3.9"


services:
  fastapi-product:
    build:
      context: .
      args:
        BUILD_ENVIRONMENT: ${BUILD_ENVIRONMENT}
    container_name: fastapi_product
    env_file:
      - .env
    ports:
      - "5011:8001"
    volumes:
      - ./:/app
    depends_on:
      - mongodb-product
      - rabbitmq-product
    networks:
      - product-fastapi
    entrypoint: /bin/sh /app/entrypoint.sh
    command: uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8001 --proxy-headers

  mongodb-product:
    image: mongo:6-jammy
    container_name: mongodb_product
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    networks:
      - product-fastapi

  mongodb-express-product:
    image: mongo-express
    container_name: mongodb_express_product
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-product
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongodb-product:27017/
    depends_on:
      - mongodb-product
    networks:
      - product-fastapi


  rabbitmq-product:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq_product
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - product-fastapi



volumes:
  rabbitmq_data:
  mongodb_data:


networks:
  product-fastapi:
    name: product-fastapi